2023-09-25 23:05:05,958 - [INFO] - 200 GET /generate_document (::1) 5.00ms
2023-09-25 23:05:06,039 - [WARNING] - 404 GET /favicon.ico (::1) 1.00ms
2023-09-25 23:06:11,324 - [INFO] - 304 GET /generate_document (::1) 2.00ms
2023-09-25 23:19:00,534 - [ERROR] - Uncaught exception GET /generate_document (::1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/generate_document', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "src/handlers\generate_file.py", line 203, in get
    "location": station["location"],
KeyError: 'location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bagrc\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\web.py", line 1786, in _execute
    result = await result
  File "src/handlers\generate_file.py", line 212, in get
    self.write(ex)
  File "C:\Users\bagrc\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\web.py", line 918, in write
    raise TypeError(message)
TypeError: write() only accepts bytes, unicode, and dict objects
2023-09-25 23:19:00,558 - [ERROR] - 500 GET /generate_document (::1) 24.98ms
2023-09-25 23:19:45,093 - [ERROR] - Uncaught exception GET /generate_document (::1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/generate_document', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "src/handlers\generate_file.py", line 203, in get
    "location": station["loc"],
KeyError: 'location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bagrc\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\web.py", line 1786, in _execute
    result = await result
  File "src/handlers\generate_file.py", line 212, in get
    self.write(ex)
  File "C:\Users\bagrc\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\web.py", line 918, in write
    raise TypeError(message)
TypeError: write() only accepts bytes, unicode, and dict objects
2023-09-25 23:19:45,094 - [ERROR] - 500 GET /generate_document (::1) 2.01ms
2023-09-25 23:19:55,410 - [INFO] - 200 GET /generate_document (::1) 2.00ms
2023-09-25 23:21:09,295 - [INFO] - 200 GET /generate_document (::1) 1.00ms
2023-09-25 23:21:47,657 - [INFO] - 200 GET /generate_document (::1) 1.99ms
